### ISSUE TITLE
[Bug] Fix the behaviour of the airdrop app when KYC is pending

### ISSUE THREAD

**Issue by olenovyk** [mento-protocol/airgrab-interface#114]
Please check this video where I described the issue I am facing:
https://www.loom.com/share/4a656b03d37f47578c04da276fc8af35

When I reopen the app while my KYC status is pending I am seeing the screen that prompts me to start KYC, instead of the screen that says "KYC is pending". Instead, it would make sense to show the screen with KYC status as pending the whole time while user is in that state.

**Comment by nvtaveras** [comment]
Didn't get to fix this but adding some context here in case someone else picks it up:

Fractal returns an access token that expires after 2 hours (according to [this](https://docs.developer.fractal.id/user-integration/user-authorization)) so at best we will be able to show the "Pending" state for 2 hours after a user first logs in with Fractal, and afterwards they will have go to through the authorization flow again. There's already a `useRefreshKYCStatus` status hook that should be doing this but it looks like it's not working properly

**Comment by bayological** [comment]
Closing as no movement on this.
