### ISSUE TITLE
[Improvement] Improve error handling 

### ISSUE THREAD

**Issue by bayological** [mento-protocol/airgrab-interface#129]
**Description**

We've seen that when the application throws an error it is not so easy to determine the cause. We should update all error handling code to include as much information as possible without causing the application to crash. 

The information we should try and add should include the following:
- What may have caused the error (e.g. calling airgrab.claim() ...)
- Where the error occurred
- Context. Additional information that can help diagnose the issue (e.g. address of connected account, connected chain, provider info etc)
- Sentry integration. Push error logs and info to sentry

**Comment by RyRy79261** [comment]
Minor updates in https://github.com/mento-protocol/airgrab-interface/pull/121 

Sentry already available but will expand existing usage
