### ISSUE TITLE
Add T&Cs page

### ISSUE THREAD

**Issue by olenovyk** [mento-protocol/airgrab-interface#66]
## Description

We need to add a Terms & Conditions page to the airdrop app. There should be a link in the footer in the same way as there is one for Imprint at mento.org
When clicked it should open a page in the new tab that looks like https://www.mento.org/imprint

[T&Cs copy](https://docs.google.com/document/d/1f3v9EPaIWsqLuoTl584YX1j6_EklH-W0/edit?usp=sharing&ouid=109498475265340717760&rtpof=true&sd=true)
## Acceptance criteria

- [x] There is a 'Terms of Service' link at the footer of airdrop app in the other section
- [x] T&Cs available on the page with url airdrop.mento.org/terms-of-service

**Comment by bayological** [comment]
Need confirmation on what "Issuing company" should be.
