### ISSUE TITLE
Add Gnosis Safe authentication support

### ISSUE THREAD

**Issue by denviljclarke** [mento-protocol/airgrab-interface#68]
## Description

We need to enable gnosis-safe wallets, which have an allocation to connect and authenticate. Currently, connecting with Gnosis Safes using RainbowKits authentication flow is not supported. Below is some more information on the issue and potential solutions. 

The leading cause of the issue is [the difference between Safe signatures & regular wallet signatures](https://forum.safe.global/t/how-to-sign-message-as-gnosis-safe/235/6) and that RainbowKit doesn't handle it in their auth flow ([The issue in the RainbowKit repo](https://github.com/rainbow-me/rainbowkit/issues/1119)). However, it seems other teams have run into this and have documented solutions. 

[Gallery](https://gallery.mirror.xyz/GzHNX1UvpNmBDQjQ0pQnE_wsdxoS0_yWocRGOssH4Xw)
[MightBear Games](https://medium.com/mighty-bear-games/how-to-handle-gnosis-safe-connection-and-signature-e4b8e62cf14d)

To add Gnosis Safe support, we'll have to implement a solution that allows them to authenticate. Maybe there's another way to handle this. Feel free to update this or add any comments. 

## Acceptance criteria

- [ ] Gnosis Safes can connect and authenticate
- [ ] Gnosis Safes can claim ( this will be harder to test unless we have a test deployment of governance on main net as app.safe.global doesn't support any testnets)

**Comment by denviljclarke** [comment]
**Story Points: 5**
  [See the discussion](https://action.parabol.co/meet/vDpD9chzpe/estimate/3) in Grooming - Mar 28

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by chapati23** [comment]
We decided we won't support claiming via Safes. Instead, we've split up the Safe allocations amongst the Safe owners so they can claim individually
