### ISSUE TITLE
Enable Vercel analytics for airdrop app

### ISSUE THREAD

**Issue by olenovyk** [mento-protocol/airgrab-interface#69]
## Description
To be able to track the funnel Impressions > app visits > tokens claimed we need to enable vercel analytics in the airdrop app

## Acceptance criteria

- [ ] Vercel analytics is enabled for an airdrop app

**Comment by bowd** [comment]
**Story Points: 2**
  [See the discussion](https://action.parabol.co/meet/vtc4Vre0og/estimate/3) in Sprint Poker #​​39

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
