### ISSUE TITLE
Implement FAQ Section Content

### ISSUE THREAD

**Issue by denviljclarke** [mento-protocol/airgrab-interface#71]
## Description
We need add actual content to the FAQ section of the website. The content to be added needs to be provided by @olenovyk. 

⚠️ Blocked until @olenovyk provides FAQ question content. 

## Acceptance Criteria

- [ ] FAQ question content is added to the app and formatted according to the design

**Comment by olenovyk** [comment]
Here is a link to FAQ version intended for airdrop app:
https://www.notion.so/mentolabs/Slim-version-of-an-FAQ-for-airdrop-app-a0e7ad88dd8d43f996579545133ba8e7?pvs=4
@denviljclarke
